# config.yaml
nc: 3

train: "/home/chanakya/chanakya/UNI/translation tool/data/images/train"
val:   "/home/chanakya/chanakya/UNI/translation tool/data/images/val"

names:
  0: Dialogue
  1: Sound Effects
  2: Signs/labels
